### ISSUE TITLE
`navbar-toggler-icon` is not visible on mobile layouts

### ISSUE THREAD

**Issue by davcri** [nCine/ncine.github.io#1]
The `navbar-toggler-icon` is not visibile when using mobile layouts (<768px).

This issue makes difficult for mobile users to discover the online documentation, examples and all the other sections of the website.

![image](https://user-images.githubusercontent.com/6860637/92638801-27571700-f2db-11ea-8284-b2f578a27316.png)

#### How to reproduce

Steps made using the latest Firefox desktop version:

1. Open https://ncine.github.io/
2. Enable [responsive design mode](https://developer.mozilla.org/en-US/docs/Tools/Responsive_Design_Mode) pressing `CTRL+SHIFT+M`
3. Set width to be less than 768px

**Comment by encelo** [comment]
Hi @davcri, and thanks for noticing this issue with the site.
It was caused by a mistake in the `_config.yml` file used by the Jekyll template that prevented the declaration of the default background color for the navigation bar in the CSS.

Please keep in mind that the repository with the site source is actually [nCine-site](https://github.com/nCine/nCine-site) and not [ncine.github.io](https://github.com/nCine/ncine.github.io).
